name: Develop to Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  prepareReleaseBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - name: Check if the submodules are correct
        run: |
          branch="${{ github.ref_name }}"
          ./scripts/git/set-submodule-branches.sh --branch "$branch"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(ci): update git submodules"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: |
            prepare-release-branch
            automated-pr
          draft: false
          title: Prepare release branch
          signoff: true
